upstream_package_name: cvetool
downstream_package_name: cvetool
specfile_path: cvetool.spec
upstream_tag_template: v{version}

jobs:
  - &fedora
    job: copr_build
    identifier: fedora
    trigger: pull_request
    enable_net: True
    targets:
      - fedora-latest-x86_64
    srpm_build_deps:
      - golang
      - go-vendor-tools
    actions:
      fix-spec-file:
        - go_vendor_archive create cvetool.spec

  - <<: *fedora
    trigger: commit
    branch: main
    preserve_project: True
    targets:
      - fedora-stable-x86_64

  - &rhel
    job: copr_build
    trigger: pull_request
    identifier: rhel
    enable_net: True
    targets:
      - rhel-10-x86_64
      - rhel-9-x86_64
      - epel-10-x86_64
      - epel-9-x86_64

    srpm_build_deps:
      - golang
    actions:
      fix-spec-file:
        - go mod tidy
        - go mod vendor
        # We wrap the tar command in bash -c so $PACKIT_PROJECT_VERSION is evaluated
        - bash -c "tar -cjvf cvetool-${PACKIT_PROJECT_VERSION}-vendor.tar.bz2 vendor/"


  - <<: *rhel
    trigger: commit
    branch: main
    preserve_project: True
