# Generated by go2rpm 1.19.0
%bcond check 1

# https://github.com/ComplianceAsCode/cvetool
%global goipath         github.com/ComplianceAsCode/cvetool
Version:                0.1.1

%gometa -L -f


Name:           cvetool
Release:        %autorelease
Summary:        A Claircore-based CVE manager

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND LicenseRef-Fedora-Public-Domain AND LicenseRef-scancode-other-permissive AND MIT AND MIT WITH LicenseRef-scancode-musl-exception AND MPL-2.0 AND (LicenseRef-Fedora-Public-Domain OR LicenseRef-scancode-other-permissive)
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
%if 0%{?fedora}
Source2:        go-vendor-tools.toml
%endif

%if 0%{?fedora}
BuildRequires:  go-vendor-tools
%endif

%description
A Claircore-based CVE manager

%prep
%goprep -p1
tar -xf %{S:1}

%generate_buildrequires
%if 0%{?fedora}
%go_vendor_license_buildrequires -c %{S:2}
%endif

%build
%global gomodulesmode GO111MODULE=on
export GO_LDFLAGS='-X main.Version=%{version}'
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%if 0%{?fedora}
%go_vendor_license_install -c %{S:2}
%endif
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%if 0%{?fedora}
%go_vendor_license_check -c %{S:2}
%endif
%if %{with check}
%gotest ./...
%endif

%if 0%{?fedora}
%files -f %{go_vendor_license_filelist}
%else
%files
%endif
%doc README.md
%{_bindir}/cvetool

%changelog
%autochangelog
